#!/usr/bin/env ruby

git_bundles = [ 
  # Latex support
  "git://github.com/vim-scripts/LaTeX-Box.git",
  # Color schemes  
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/mrtazz/molokai.vim.git",
  "git://github.com/goatslacker/mango.vim.git",
  "git://github.com/nanotech/jellybeans.vim.git",
  # Autoclose brackets
  "git://github.com/vim-scripts/Auto-Pairs.git",
]

vim_org_scripts = [
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  if script_type == 'zip'
    local_file = File.join(name, "#{name}.#{script_type}")
  else
    local_file = File.join(name, script_type, "#{name}.vim")
  end
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    `unzip #{local_file} -d #{name}`
    FileUtils.rm_rf(local_file)
  end
end

